### ISSUE TITLE
Add snackbar for RSS-Feeds feature.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#112]
**Is your feature request related to a problem? Please describe.**
Adding a snackbar for RSS-Feed feature would increase the user experience as the user would be able to get a confirmation if a particular RSS-Feed/Download Rules is added or not.

**Describe the solution you'd like**
- Add a snackbar for adding an RSS-Feed.
-  Add a snackbar for adding a Download Rule.

**Additional context**
Sample of snackbar implemented for on delete torrent feature.

https://user-images.githubusercontent.com/73401649/206924331-87ac3efb-4678-4b2e-9eea-6b2d53c07180.mp4

**Comment by letsintegreat** [comment]
Requesting to be assigned!

**Comment by Akshatji800** [comment]
@letsintegreat assigning this issue to you.
