### ISSUE TITLE
Snackbar for add new user and add new torrent not working.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#114]
**Describe the bug**
Snackbar for add new user and add new torrent not working.

**To Reproduce**

1. Try adding a new torrent and no snackbar will appear although it is implemented.
2. Try adding a new user using the settings option and no snackbar will appear although it is implemented.

**Expected behavior**
Respective snackbar should appear on adding a new torrent/user.

**Comment by ManavSarkar** [comment]
Shall I work on this issue?

**Comment by Akshatji800** [comment]
Yeah @ManavSarkar  please go ahead. I will assign the issue to you.

**Comment by ManavSarkar** [comment]
![image](https://user-images.githubusercontent.com/42129636/207239843-69a660d2-e16e-4a25-9792-145acf483767.png)
![image](https://user-images.githubusercontent.com/42129636/207240099-ce103e27-4076-4be6-beb4-1f3e8624ca31.png)

I am getting this error. 
This is the localhost version.
Tried the following remedies but didn't work:

- npm cache clean
- uninstalled flood and qbittorrent
- installed a lower version qbittorrent

And with IP address
![image](https://user-images.githubusercontent.com/42129636/207240190-e6d60539-7432-46ae-97af-6833784e0746.png)
Above error is showing

**Comment by ManavSarkar** [comment]
@Akshatji800 I have installed Flood and qBittorrent but I am getting the following error after following the contributing.md guide.
![image](https://user-images.githubusercontent.com/42129636/207243432-0aff76cf-c301-4bb8-aefd-f43e89027fae.png)

I have tried to clear NPM cache, uninstall and then re install but it didn't work.
Can you please help me out?
In Flood, I am getting the following error in Terminal
![image](https://user-images.githubusercontent.com/42129636/207243634-19d714a5-7a5c-42f8-ae5d-03ae679a3b73.png)

**Comment by Akshatji800** [comment]
> @Akshatji800 I have installed Flood and qBittorrent but I am getting the following error after following the contributing.md guide. ![image](https://user-images.githubusercontent.com/42129636/207243432-0aff76cf-c301-4bb8-aefd-f43e89027fae.png)
> 
> I have tried to clear NPM cache, uninstall and then re install but it didn't work. Can you please help me out? In Flood, I am getting the following error in Terminal ![image](https://user-images.githubusercontent.com/42129636/207243634-19d714a5-7a5c-42f8-ae5d-03ae679a3b73.png)

@ManavSarkar  there is some issue with qBittorent and flood which needs to be addressed and resolved until then you can use transmission instead of qBittorent. The setup is almost similar.

**Comment by ManavSarkar** [comment]
> > @Akshatji800 I have installed Flood and qBittorrent but I am getting the following error after following the contributing.md guide. ![image](https://user-images.githubusercontent.com/42129636/207243432-0aff76cf-c301-4bb8-aefd-f43e89027fae.png)
> > I have tried to clear NPM cache, uninstall and then re install but it didn't work. Can you please help me out? In Flood, I am getting the following error in Terminal ![image](https://user-images.githubusercontent.com/42129636/207243634-19d714a5-7a5c-42f8-ae5d-03ae679a3b73.png)
> 
> @ManavSarkar there is some issue with qBittorent and flood which needs to be addressed and resolved until then you can use transmission instead of qBittorent. The setup is almost similar.

it is fixed
