### ISSUE TITLE
Improving the theme-changing feature and adding an animation to it to make the theme switching look better.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#117]
**Is your feature request related to a problem? Please describe.**
Currently the animation looks a bit weird while changing the theme from dark mode to light mode and vice versa.

**Describe the solution you'd like**
The theme-changing feature can be improved by adding an animation to it to make the theme switching look better.

**Additional context**
Sample implementation:
![1_gZTqvTmrf4rq9rMYtyMI8g](https://user-images.githubusercontent.com/73401649/207030932-ca6ce74e-eb45-4559-938a-affc4e83d841.gif)

**Comment by sainideepanshu199** [comment]
please assign this issue to me.

**Comment by Akshatji800** [comment]
@sainideepanshu199  please take one issue at a time. You can surely take other issues once you are done with solving the previous issues assigned.

**Comment by sainideepanshu199** [comment]
> @sainideepanshu199 please take one issue at a time. You can surely take other issues once you are done with solving the previous issues assigned.

sure! i will work on one issue at once

**Comment by letsintegreat** [comment]
I would like to work on this issue, please assign it to me.

**Comment by harsv689** [comment]
Can I work upon this issue?

**Comment by Akshatji800** [comment]
Assigning this issue to @letsintegreat.

**Comment by Akshatji800** [comment]
> Can I work upon this issue?

@harsv689 please have a look at the other existing issues reported and ask them to assign it to you. For this issue since it was first claimed by @letsintegreat so it was assigned to him. Hope it works for you.

**Comment by amitamrutiya2210** [comment]
Hey @letsintegreat are you working on this issue?

**Comment by Akshatji800** [comment]
> Hey @letsintegreat if you are not working on this issue then I want to work on this issue.

Hey @amitamrutiya2210 do you still want to work on this issue? If yes then please let me know and I will assign this issue to you.

**Comment by sainideepanshu199** [comment]
i am willing to work on thus issue please assign it to me

**Comment by Akshatji800** [comment]
> i am willing to work on thus issue please assign it to me

@sainideepanshu199 assigning this issue to you. You can continue with the same changes made in the [PR-133](https://github.com/CCExtractor/Flood_Mobile/pull/133) and solve the issues reported by me in the PR (issues are mentioned at the end of the PR conversations tab).

**Comment by sainideepanshu199** [comment]
can u please help me solve this setup issue i am facing it again 
![image](https://user-images.githubusercontent.com/114583893/222955406-0656a277-7d26-4bf4-bf34-2a997703a1f3.png)

**Comment by sainideepanshu199** [comment]
> > i am willing to work on thus issue please assign it to me
> 
> @sainideepanshu199 assigning this issue to you. You can continue with the same changes made in the [PR-133](https://github.com/CCExtractor/Flood_Mobile/pull/133) and solve the issues reported by me in the PR (issues are mentioned at the end of the PR conversations tab). Hope to see a fix soon as I want this to be a part of our new release

please help me in setup of the project , its very confusing

**Comment by amitamrutiya2210** [comment]
For solve this error, while installing you have to install this Web Interface Option.

![Screenshot_2023-03-05-21-42-52-391_com android chrome](https://user-images.githubusercontent.com/91112485/222972211-109d2328-8bb1-4d39-b21b-c262d1229ae3.png)
