### ISSUE TITLE
Contributing.md file is not updated

### ISSUE THREAD

**Issue by AntoTomAbraham** [CCExtractor/Flood_Mobile#126]
In the contributing.md file its saying that, for qBittorent, click on the preference to set up the Web UI, but nothing like preference is present in the qBittorent UI
<img width="689" alt="Capture" src="https://user-images.githubusercontent.com/64683098/208810667-c43b5994-3e4f-4493-8d7d-12f04f3bfa6c.PNG">

**Comment by Akshatji800** [comment]
Issue resolved by the #124
