### ISSUE TITLE
Add snackbar on deleting a rss-feed/download rule.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#127]
**Is your feature request related to a problem? Please describe.**
A snackbar can be shown on deleting a rss-feed/download rule to notify the user about the deletion process.

**Describe the solution you'd like**
Add snackbar on deleting a rss-feed/download rule.

**Additional context**
A download rule/rss-feed can be deleted by clicking on the delete icon beside a particular rss-feed/download rule.

**Comment by amitamrutiya2210** [comment]
While my PR has been review can i work on this issue?

**Comment by Akshatji800** [comment]
Sure @amitamrutiya2210 assigning the issue to you.

**Comment by amitamrutiya2210** [comment]
I think on deleting undo option is good in snackbar rather than dismiss button .
