### ISSUE TITLE
Issue in add torrent page checkboxes.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#128]
**Describe the bug**
There is an issue in add torrent page checkboxes that the state of the checkboxes (use as base path checkbox, sequential download checkbox, completed checkbox) does not change even on selecting/unselecting them.

**To Reproduce**

1. Go to 'home-screen' and click on add button at the right bottom.
2. Click on 'magnet/file icon'.
3. Try clicking on any of the checkboxes.
4. You will find no state change in checkboxes even after clicking on them.

**Expected behavior**
State of the checkbox should be changed clearly on selecting them.

**Comment by Sudhanva-Nadiger** [comment]
hey can you assign this issue to me ?

**Comment by Akshatji800** [comment]
Sure @Sudhanva-Nadiger assigning the issue to you.

**Comment by Sudhanva-Nadiger** [comment]
hey i am unable to set the app locally in my system, the login to flood is not happening, i tried to join slack, but its asking tokens, can you help me set the app?

**Comment by amitamrutiya2210** [comment]
Hey @Sudhanva-Nadiger read this part in CONTRIBUTING.md for setup in your device :[https://github.com/CCExtractor/Flood_Mobile/blob/master/CONTRIBUTING.md#login-into-app](url)
I hope it will help you

**Comment by Sudhanva-Nadiger** [comment]
I have been trying to set up the app from this instructions only
but its showing that the connection could not be verified !!

**Comment by Sudhanva-Nadiger** [comment]
# qbittorrent web ui
![image](https://user-images.githubusercontent.com/93595710/210554005-c3013713-bb88-455a-b1ec-f146814ee09f.png)

# flood web ui
![image](https://user-images.githubusercontent.com/93595710/210554291-5936da88-6c63-4677-9402-3f8c7bb5612c.png)

# Error in console
![image](https://user-images.githubusercontent.com/93595710/210554626-94cfc725-609d-4a34-92a2-16d006b4df88.png)

**Comment by amitamrutiya2210** [comment]
`http://127.0.0.1:3000/` Is this ip you use for flood web ui ?

**Comment by Akshatji800** [comment]
@Sudhanva-Nadiger were you able to solve the issue you were facing while setting up the project? If not then this is what you need to do to resolve the issue.

Uninstall the older version of flood u have by using the command `sudo npm uninstall -g flood` and install the latest but not released version by using the command `sudo npm i -g @jesec/flood`

**Comment by amitamrutiya2210** [comment]
Yes it's looks like this. You are on right track.

**Comment by amitamrutiya2210** [comment]
Yes it's looks like this. You are on right track.

**Comment by amitamrutiya2210** [comment]
Yes it's looks like this. You are on right track.

**Comment by Sudhanva-Nadiger** [comment]
Getting these error while running :(
Which version the app is using ?
![image](https://user-images.githubusercontent.com/93595710/212387635-4e13abaf-5b23-43a8-a559-366386a1c4bc.png)

**Comment by amitamrutiya2210** [comment]
Yes it's looks like this. You are on right track. Go ahead ...

**Comment by amitamrutiya2210** [comment]
There is multiple reasons for `app:compileflutterbuilddebug` this error . You can try solutions from this [https://stackoverflow.com/questions/61930007/how-to-solve-execution-failed-for-task-appcompileflutterbuilddebug](url).

**Comment by Sudhanva-Nadiger** [comment]
App is up and running !!! soon  i will add the required things !!! thanks guys for the help

**Comment by Sudhanva-Nadiger** [comment]
@Akshatji800 the checkbox should remember the lastValue when its opened again ?

**Comment by amitamrutiya2210** [comment]
![Screenshot_1673682943 (Custom)](https://user-images.githubusercontent.com/91112485/212462309-a36af8bf-0e8f-47a2-b492-12a6ba67be59.png)
if you tap any of this checkbox then state of checkbox like select/unselect not reflected on the screen you have to fix this .

**Comment by Sudhanva-Nadiger** [comment]
-okay I think I have solved the problem !! Take a look at it.

https://user-images.githubusercontent.com/93595710/212462379-5351b4d9-0898-41a3-9b3f-01b385c88b95.mp4

**Comment by Sudhanva-Nadiger** [comment]
-okay I think I have solved the problem !! Take a look at it.

https://user-images.githubusercontent.com/93595710/212462379-5351b4d9-0898-41a3-9b3f-01b385c88b95.mp4

**Comment by Sudhanva-Nadiger** [comment]
Should I send pull request?

**Comment by amitamrutiya2210** [comment]
Yes

**Comment by amitamrutiya2210** [comment]
Yes

**Comment by Sudhanva-Nadiger** [comment]
Will do that tomo !!

**Comment by Akshatji800** [comment]
@amitamrutiya2210 thanks for clearing @Sudhanva-Nadiger doubts and helping him in moving forward with the issue in mine absence. This really demonstrate the quality of a good open source contributor in you.

**Comment by amitamrutiya2210** [comment]
Thank you @Akshatji800
