### ISSUE TITLE
Add user accounts displaying section under authentication in the settings.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#129]
**Is your feature request related to a problem? Please describe.**
User accounts displaying section can be added under authentication in the settings in the same way as it is currently in the flood web app.

**Describe the solution you'd like**
User accounts displaying section under authentication in the settings can be added.

**Additional context**
![imageedit_0_5712601901](https://user-images.githubusercontent.com/73401649/209241346-3218c47b-cc15-40ef-b277-cc4093427ac3.png)

**Comment by letsintegreat** [comment]
Requesting to be assigned.

**Comment by Akshatji800** [comment]
@letsintegreat assigning the issue to you. Hope to see the enhancement soon :)

**Comment by amitamrutiya2210** [comment]
Hey @letsintegreat are you working on this issue?

**Comment by Akshatji800** [comment]
> Hey @letsintegreat if you are not working on this issue then I want to work on this issue.

Hey @amitamrutiya2210 if you still want to work on this issue then please let me know and I will assign this issue to you.

**Comment by amitamrutiya2210** [comment]
I want to work on this issue.

**Comment by Akshatji800** [comment]
> I want to work on this issue.

Sure @amitamrutiya2210 I will assign this issue to you. Continue in the same PR from where @letsintegreat left. See what were the last changes requested by me from @letsintegreat in the PR and are yet to be implemented.
