### ISSUE TITLE
Theme bug in the add torrent page.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#130]
**Describe the bug**
There is a theme bug in the add torrent page which can be noticed when the app is in light mode.

**To Reproduce**

**Note:** App should be in light mode.
1. Go to 'home-screen' and click on add magnet/torrent file icon.
2. Add torrent page will appear with a theme bug.

**Expected behavior**
The page theme should be matched in light mode also with the page's current theme.

**Screenshots
![photo_2022-12-23_10-39-21](https://user-images.githubusercontent.com/73401649/209243198-8767dc2f-3cea-4f9f-bdcd-4e0ebbb951bc.jpg)
**

**Comment by ManavSarkar** [comment]
Shall I fix this issue?

**Comment by Akshatji800** [comment]
@ManavSarkar assigning the issue to you. Hope to see a quick fix.

**Comment by ManavSarkar** [comment]
This issue is fixed, kindly check the previous one so that I can add this as well.

**Comment by Akshatji800** [comment]
> This issue is fixed, kindly check the previous one so that I can add this as well.

@ManavSarkar you can raise a seperate PR solving this issue as well

**Comment by Karmpatel960** [comment]
hey @Akshatji800 Can i work on it?

**Comment by ManavSarkar** [comment]
> hey @Akshatji800 Can i work on it?

Actually this is fixed.

**Comment by Karmpatel960** [comment]
Hey @ManavSarkar but this issue is still there in app

**Comment by ManavSarkar** [comment]
because the PR hasn't been merged. @Karmpatel960 kindly check in the PR section

**Comment by amitamrutiya2210** [comment]
Hey @ManavSarkar , if you click on the download button in the feeds, a similar bottom sheet opens. There is also an issue with it. Fixing it with this pull request would be great.

![Screenshot_1675339202 (Medium) (Small)](https://user-images.githubusercontent.com/91112485/216320011-e01f7f88-69ad-426e-a2a4-563390075522.png)

**Comment by ManavSarkar** [comment]
Okay, @amitamrutiya2210 I haven't checked that. Thank you for letting me know. Okay I am fixing that soon

**Comment by amitamrutiya2210** [comment]
Before commit changes wait for @Akshatji800 conformation?

**Comment by Akshatji800** [comment]
@ManavSarkar please resolve the issue @amitamrutiya2210 mentioned above in the #147 PR itself. Hope to see a fix soon. Also don't forget to squash the commits.

**Comment by ManavSarkar** [comment]
@amitamrutiya2210 yeah the errors are fixed, all the theme errors are fixed.

https://user-images.githubusercontent.com/42129636/218300600-e610d9c1-67da-4024-8625-54a46e53fadd.mp4

**Comment by amitamrutiya2210** [comment]
@ManavSarkar here you have to add outline boarders around this container. This board is visible in dark mode but not visible in light mode.
![Screenshot 2023-02-12 163218 (New size 1)](https://user-images.githubusercontent.com/91112485/218307206-6537ebdf-48fc-4421-818e-36581b87d776.png)

**Comment by ManavSarkar** [comment]
@amitamrutiya2210 Yeah I haven't noticed that. Okay will add it today only.

**Comment by ManavSarkar** [comment]
@Akshatji800 here is new attached output

https://user-images.githubusercontent.com/42129636/219589747-e6e4c863-de79-4573-aecb-5f9f0394f7db.mp4
