### ISSUE TITLE
Theme bug in rss-feed and download rules page in light mode.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#131]
**Describe the bug**
Theme bug in rss-feed and download rules page in light mode. The existing feeds/existing rules textbox  boundary is not visible in light mode but is perfectly fine in dark mode of the app.

**To Reproduce**

1. Go to 'home-screen' and click of rss-feed icon on the top right corner.
2. Issue can be noticed on both rss-feed/download rules pages.

**Expected behavior**
Boundary of the box should be clearly visible as in dark mode of the app.

**Screenshots**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244222-d42b137a-0968-4570-ae40-fd13f3081a70.jpg" width="250"> <br /><b>Light-Mode(RSS-Feed)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244667-a94f4cdd-35d3-43e1-8724-bf38c0ce8f01.jpg" width="250"><br /><b>Dark-Mode(RSS-Feed)</b></a><br /></td>
</tr>
</table>

<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244949-f1d46a76-042a-4a32-8e5f-fa82ec3891c3.jpg" width="250"> <br /><b>Light-Mode(Download Rules)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244868-2b6888a2-9d98-42b7-8677-3e6e9b414f3e.jpg" width="250"><br /><b>Dark-Mode(Download Rules)</b></a><br /></td>
</tr>
</table>

**Comment by amitamrutiya2210** [comment]
@Akshatji800 Can you assign this issue to me?

**Comment by Akshatji800** [comment]
@amitamrutiya2210 assigning the issue to you. Hope to see a fix soon.
