### ISSUE TITLE
Display the size beside each tracker listed under filter by trackers.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#132]
**Is your feature request related to a problem? Please describe.**
The size can be displayed beside each tracker listed under filter by trackers in the same way as in the flood web app.

**Describe the solution you'd like**
Display the size beside each tracker listed under filter by trackers.

**Additional context**
![Screenshot_38](https://user-images.githubusercontent.com/73401649/209245555-86487086-898d-4417-8b68-fc49da3d9a05.png)

**Comment by ManavSarkar** [comment]
Shall I take this issue? I will be able to do it.

**Comment by Akshatji800** [comment]
@ManavSarkar assigning this issue to you.

**Comment by Akshatji800** [comment]
@ManavSarkar is there any update on the your progress while resolving this issue?

**Comment by ManavSarkar** [comment]
Hi, the TorrentModel file has the detail of the size of the torrents. Now should I add the List of sizes in the FilterProvider.

**Comment by ManavSarkar** [comment]
@ The feature has been added. Kindly check my previous PR so that I can add it as soon as possible.
