### ISSUE TITLE
Fix notification dialogue in light mode

### ISSUE THREAD

**Issue by amitamrutiya2210** [CCExtractor/Flood_Mobile#140]
**Describe the bug**
FIx some colors in light and dark mode

**Expected behavior**
Make it clearly visible in light and dark mode

**Screenshots**
![Screenshot_1672993168 (Custom)](https://user-images.githubusercontent.com/91112485/211048547-728b8fb5-077e-492e-878a-2cd29fb7dfcd.png)   ![Filter_light_theme (Custom)](https://user-images.githubusercontent.com/91112485/211048549-63d59d62-3766-4b59-ac3d-9f257130cf62.png) 
 ![delete sheet (Custom)](https://user-images.githubusercontent.com/91112485/211048551-93e9ab07-16ab-4ab5-ac1a-e74eec17aca8.png)  ![high_priority (Custom)](https://user-images.githubusercontent.com/91112485/211048556-52a80f18-6c2d-41ac-9ffe-1a1bd10e71fd.png)

**Additional context**
Color has been change accordingly to default theme.

**Are you working on this issue?**
Yes

**Comment by rutuja1121** [comment]
Hello, I understood the issue but could you tell me if this repo is only for GSoC students?

**Comment by amitamrutiya2210** [comment]
No, it' is an open source repo anyone can contribute in this repo and other CCExtractor projects .
