### ISSUE TITLE
Theme bug in rss-feed and download rules page in light mode after adding a rule/feed.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#149]
**Describe the bug**
Theme bug in rss-feed and download rules page in light mode. The existing feeds/existing rules textbox boundary is not visible in light mode but is perfectly fine in dark mode of the app when the user adds a feed/rule.

**To Reproduce**

1. Go to 'home-screen' and click of rss-feed icon on the top right corner.
2. Add an rss-feed/rule.
3. Issue can be noticed on both rss-feed/download rules pages.

**Expected behavior**
Boundary of the box should be clearly visible as in dark mode of the app even after adding a feed/rule.

**Screenshots**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244222-d42b137a-0968-4570-ae40-fd13f3081a70.jpg" width="250"> <br /><b>Light-Mode(RSS-Feed)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/209244667-a94f4cdd-35d3-43e1-8724-bf38c0ce8f01.jpg" width="250"><br /><b>Dark-Mode(RSS-Feed)</b></a><br /></td>
</tr>
</table>

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by Akshatji800** [comment]
> Can I work on this ?

Sure @Sudhanva-Nadiger but first please give priority to the issue assigned to you. Once you resolve that issue then you can surely come and take this issue as well.

**Comment by AntoTomAbraham** [comment]
Can you assign this issue to me ?

**Comment by Akshatji800** [comment]
> Can you assign this issue to me ?

Sure @AntoTomAbraham assigning this issue to you.

**Comment by Sudhanva-Nadiger** [comment]
@Akshatji800 i have solved the other issue

**Comment by Akshatji800** [comment]
> @Akshatji800 i have solved the other issue, sending pr is remaining

Issue counts as solved only when a PR is sent atleast. Think of the fact that how can I know that you solved a particular issue if you won't do a PR after solving the issue. Please do a PR for the previous issue you solved. There are many issues open for you to take over apart from the current issue. Hope you understand.

**Comment by Sudhanva-Nadiger** [comment]
Yeah I have sent pr for the previous issue ! I was waiting for you to tell that I can send pr because I did not know how you wanted the issue to be solved. Anyways :(

**Comment by sooraj-24** [comment]
Hi @Akshatji800, I would like to work on this issue, is it still open?

**Comment by AntoTomAbraham** [comment]
> Hi @Akshatji800, I would like to work on this issue, is it still open? 

Already solved this issue, waiting for the PR to get merged
