### ISSUE TITLE
maintenance: migrating code base to null-safety

### ISSUE THREAD

**Issue by prajwal27** [CCExtractor/Flood_Mobile#15]
Hello, 
The current codebase is using unsound null safety, which isn't safe. If migrated to null-safety, it's better.

**Comment by mail-man26** [comment]
I would like to work on this issue

**Comment by pratikbaid3** [comment]
@mail-man26 I have assigned this issue to you.

**Comment by mail-man26** [comment]
> @mail-man26 I have assigned this issue to you.

Thanks for assigning!! I am working on it

**Comment by pratikbaid3** [comment]
@mail-man26 are you still working on this issue?

**Comment by prajwal27** [comment]
@pratikbaid3  can I work on it this time?

**Comment by pratikbaid3** [comment]
@prajwal27 Sure, I don't think @mail-man26 is working on it. I'll assign it to you.

**Comment by prajwal27** [comment]
@pratikbaid3  the contributing guidelines are absent. Should I fork this repo and make a PR or should I create a branch and make PR?

**Comment by pratikbaid3** [comment]
@prajwal27 please refer to CONTRIBUTING.md. You can use the develop branch to create a fork and then make a PR.

**Comment by prajwal27** [comment]
@pratikbaid3 , the project is using another local package `flutter_client_sse`, that probably needs to be migrated first.

**Comment by pratikbaid3** [comment]
@prajwal27 you can comment out the local package usage for now and use the one on pub.dev. That was done to make quick changes in the package itself. The package on pub.dev would be at par with the local package for the most part so it shouldn't cause any issues. If it is does, feel free to open an issue on https://github.com/pratikbaid3/flutter_client_sse.

**Comment by pratikbaid3** [comment]
Resolved in #22
