### ISSUE TITLE
home_screen_widget_test.dart page widget tests failing.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#150]
**Describe the bug**
The home_screen_widget_test.dart page widget tests have started failing after the new features added to the screen.

**To Reproduce**

1. Go to android-studio and navigate to test folder.
2. Search for home_screen_widget_test.dart file and run the widget test by clicking on the green run button beside the main function.
3. Widget test written in the home_screen_widget_test.dart file will start running.
4. See errors.

**Expected behavior**
The widget tests failing should be changed and should be written according to the new features implemented so that they should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/73401649/212531209-0d0d8f06-84a1-446f-b3d8-5d1f57a938ae.png)

**Comment by Sudhanva-Nadiger** [comment]
I would like to work on this !

**Comment by Akshatji800** [comment]
> I would like to work on this !

Sure @Sudhanva-Nadiger assigning this issue to you.

**Comment by adilwahla** [comment]
@Akshatji800  would love to fix the issue assign it to me please
