### ISSUE TITLE
torrent_screen_widget_test.dart page widget tests failing.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#151]
**Describe the bug**
The torrent_screen_widget_test.dart page widget tests have started failing after the new features added to the screen.

**To Reproduce**

1. Go to android-studio and navigate to test folder.
2. Search for torrent_screen_widget_test.dart file and run the widget test by clicking on the green run button beside the main function.
3. Widget test written in the torrent_screen_widget_test.dart file will start running.
4. See errors.

**Expected behavior**
The widget tests failing should be changed and should be written according to the new features implemented so that they should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/73401649/212531565-48ccf4db-cfa7-4da4-b4f3-8b99b9cb1107.png)

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this?

**Comment by Akshatji800** [comment]
Sure @Sudhanva-Nadiger assigning this issue to you.

**Comment by Sudhanva-Nadiger** [comment]
@Akshatji800 can you update the readme.md ? because there is been a change in the layout and architecture of add torrent page! to write a test I need a demo for it! tests for magnet link click is done, but when clicking on torrent file what should happen is I wanted to check.

**Comment by aryamanshrivastava** [comment]
@Akshatji800 Could you kindly grant me permission to work on this issue?
