### ISSUE TITLE
Keyboard hides text field while adding magnet URL

### ISSUE THREAD

**Issue by ishaandwivedi1234** [CCExtractor/Flood_Mobile#157]
**Describe the bug**
While adding a magnet URL link keyboard hides the destination text field and also the subsequent checkboxes which makes it inconvenient to add the torrent through the link.

**To Reproduce**
1. Open the app
2. On the torrent's page tap on the '+' icon 
3. Tap on the magnet link
4. Now try adding the magnet URL 

**Expected behavior**
The bottom sheet should be scrollable after the keyboard is popped up.

**Screenshots**
![Untitled (1)](https://user-images.githubusercontent.com/50709505/213268647-a2e23c5f-e65f-4021-a642-d7f10a82568d.gif)

**Device Information:**
   iOS & Android

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Akshatji800** [comment]
@ishaandwivedi1234 this looks a legit issue to be worked on. You can continue working on this issue. I am assigning this issue to you.

**Comment by MrNitishroy** [comment]
want to work on this issue, please assign me

**Comment by ishaandwivedi1234** [comment]
Hey @MrNitishroy already stared, WIP

**Comment by ishaandwivedi1234** [comment]
Hi @Akshatji800 !! Please do review this PR, if everything seems fine.
