### ISSUE TITLE
Notify user when press back button for exit

### ISSUE THREAD

**Issue by amitamrutiya2210** [CCExtractor/Flood_Mobile#162]
**Is your feature request related to a problem? Please describe.**
If the user accidentally presses the back button on the home page, the app will minimize. The user will also be notified if they accidentally press the back button.

**Describe the solution you'd like**
 User must press the back button twice continuously to exit the app.

**Additional context**
A toast message will also appear if the user only taps the back button once.

**Are you working on this? (Yes/No)**
Yes

**Comment by Akshatji800** [comment]
@amitamrutiya2210 this looks like a legit issue to be worked on. Assigning this issue to you.

**Comment by Interstellar07** [comment]
@amitamrutiya2210  hey..are you working on this issue?

**Comment by amitamrutiya2210** [comment]
Hey @Interstellar07 i already submitted PR regarding this issue
