### ISSUE TITLE
Text overflow issue in snackbar

### ISSUE THREAD

**Issue by divz-codess** [CCExtractor/Flood_Mobile#163]
**Describe the bug**
While displaying longer messages the text overflows in the snackbar. To avoid text overflow while displaying longer text messages in future the flood snackbar should be fixed.

**To Reproduce**
- While displaying any longer text message in snackbar.

**Expected behavior**
- Longer texts should wrap inside the snackbar.

**Screenshots**
![snackbarissue](https://user-images.githubusercontent.com/88512639/213537210-7c117182-5940-486c-ab0d-c316ffeca908.jpeg)

**Device Information [optional]:**
- iOS/Android

**Are you working on this issue? (Yes/No)**
YES :)

**Comment by Akshatji800** [comment]
@divz-codess which snackbar is having this issue. Please clarify if this is a legit issue or not before working on it.

**Comment by divz-codess** [comment]
The addFloodSnackbar() function has this overflow issue while displaying long text messages.
