### ISSUE TITLE
Filter by Track is not update when delete torrent

### ISSUE THREAD

**Issue by amitamrutiya2210** [CCExtractor/Flood_Mobile#171]
**Describe the bug**
After delete torrent if we open filter then we show old trackers list that are deleted.

**Expected behavior**
Update filter information after deleting any torrent

https://user-images.githubusercontent.com/91112485/215066001-b3332fc8-d222-4f56-9bdd-362b280bf077.mp4

**Are you working on this issue? (Yes/No)**
Yes

**Comment by cscipher** [comment]
is anyone working on this issue? If not, then I would like to pick this up

**Comment by amitamrutiya2210** [comment]
@cscipher i already submitted pull request on this issue.
