### ISSUE TITLE
Update readme.md with new pictures of the app screens

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [CCExtractor/Flood_Mobile#173]
**Is your feature request related to a problem? Please describe.**
- Currently readme.md contains the old version app photos.

**Describe the solution you'd like**
- Update those with new pictures

**Comment by Sudhanva-Nadiger** [comment]
@Akshatji800 please add first timer only tag to this issue. Thanks!

**Comment by Akshatji800** [comment]
> @Akshatji800 please add first timer only tag to this issue. Thanks!

@Sudhanva-Nadiger do you want to take this issue or should I assign it to @Adiii1436 ?

**Comment by Sudhanva-Nadiger** [comment]
Assign this to @Adiii1436 ! No problem

**Comment by Adiii1436** [comment]
Yes please assign me the issue @Akshatji800

**Comment by SakshamSahu** [comment]
I can update readme.md with new pictures of the updated app, can you please assign this issue to me?

**Comment by cfsmp3** [comment]
Just send a PR.

**Comment by virajbhartiya** [comment]
Is it okay if I work on this since no PR is submitted yet?

**Comment by Akshatji800** [comment]
> Is it okay if I work on this since no PR is submitted yet?

Go ahead if you think you can send a PR quickly. 
Currently I am not assigning this issue to anyone as it is a very basic job. The first PR will be considered as  a legit PR.

**Comment by virajbhartiya** [comment]
Are just normal screenshots okay or do you want them displayed in an emulator skin?

**Comment by virajbhartiya** [comment]
Are just normal screenshots okay or displayed in an emulator skin?

**Comment by Akshatji800** [comment]
> Are just normal screenshots okay or displayed in an emulator skin?

See if you can make something like the images under Application Preview in this repo readme.
https://github.com/Akshatji800/Relive

**Comment by Akshatji800** [comment]
> > Are just normal screenshots okay or displayed in an emulator skin?
> 
> See if you can make something like the images under Application Preview in this repo readme. https://github.com/Akshatji800/Relive

Canva was used to make this

**Comment by virajbhartiya** [comment]
Okay got it. I'll start working on this

**Comment by virajbhartiya** [comment]
Hey @Akshatji800, I've updated the screenshots. They are in a bit different format but we can add some sort of text at the top of the images if that's what is required.
Let me know your views.

**Comment by virajbhartiya** [comment]
Okay sure, I'll make the changes and send the PR.

**Comment by virajbhartiya** [comment]
Hey @Akshatji800, I've committed new screenshots to the PR. Please take a look.

**Comment by Akshatji800** [comment]
> Hey @Akshatji800, I've committed new screenshots to the PR. Please take a look.

Again the same issue continues. Weird alignment of the screenshot inside the emulator border component

**Comment by virajbhartiya** [comment]
Please check the updated screenshots.

**Comment by virajbhartiya** [comment]
Hey @Akshatji800, Please take a look at the updated screenshots.

**Comment by Akshatji800** [comment]
> Hey @Akshatji800, Please take a look at the updated screenshots.

Hey @virajbhartiya ig there is still a lot of scope of improvements. You can use this website to create the mockups and then combine them in canva. Also make sure you include all the features included in the previous readme along with adding the new features

**Comment by virajbhartiya** [comment]
Hey @Akshatji800, I've updated the screenshots. I haven't made a collage of them so they can be aligned as per the screen size on the readme. But I've set their size in which they'll be visible in the readme
Please review it

**Comment by Akshatji800** [comment]
> Hey @Akshatji800, I've updated the screenshots. I haven't made a collage of them so they can be aligned as per the screen size on the readme. But I've set their size in which they'll be visible in the readme Please review it

@virajbhartiya can you please use black frame mockup device and keep the full screenshot without cropping it from top and bottom.
For example:
![smartmockups_levxm7ji](https://user-images.githubusercontent.com/73401649/222988317-696e7314-445f-4e05-b22a-c4762d5ed114.jpg)

**Comment by virajbhartiya** [comment]
Sure @Akshatji800, I've made the changes, black frame, no notch, even the camera isn't overlapping with the screenshot, and it's the full screenshot
Please review it
