### ISSUE TITLE
Clear filter feature on no torrent display

### ISSUE THREAD

**Issue by amitamrutiya2210** [CCExtractor/Flood_Mobile#180]
**Is your feature request related to a problem? Please describe.**
Currently when user applies any filter and there is no filtered torrent then user seen blank scrren.

**Describe the solution you'd like**
In this situation if user see `no torrent to display` text and `clear filter` button that clear applied filter then it will good.

**Additional context**
This feature available in flood web ui.

**Are you working on this? (Yes/No)**
Yes

**Comment by Arnav2001** [comment]
I also want to contribute kindly assign me good first issues.
