### ISSUE TITLE
Enhancement in the intro page

### ISSUE THREAD

**Issue by Krish-Code01** [CCExtractor/Flood_Mobile#183]
**Skip button and and Text is overlapping with the background**

**Expected behavior**
Text and Skip button in the intro screen should not overlap with the container in the background. Both text and skip button must be shifted upwards or a border can be added.

**Screenshots**
<img width="358" alt="Screenshot 2023-02-07 at 9 31 24 PM" src="https://user-images.githubusercontent.com/90051155/217300034-71eeabce-7a8a-481d-86ad-1b8ecd8f1db3.png">
<img width="358" alt="Screenshot 2023-02-07 at 9 31 31 PM" src="https://user-images.githubusercontent.com/90051155/217299948-03031e0e-9bdf-4604-a4ba-8d5e4ac0172c.png">

**Are you working on this issue? (Yes/No)**
Yes

**Comment by bhav-khurana** [comment]
@Krish-Code01 are you still working on this issue?

**Comment by cscipher** [comment]
is anyone working on this issue? If not, then I would like to pick this up

**Comment by virajbhartiya** [comment]
I've fixed this issue please review it. If any changes are required do let me know.

**Comment by Akshatji800** [comment]
@Krish-Code01 do you still want to work on this or you are okay with me assiging it to anyone else?

**Comment by Krish-Code01** [comment]
No, I am working on it

**Comment by Krish-Code01** [comment]
@Akshatji800 Made a PR kindly check it.
