### ISSUE TITLE
Snackbar on set download and upload speed

### ISSUE THREAD

**Issue by amitamrutiya2210** [CCExtractor/Flood_Mobile#185]
**Is your feature request related to a problem? Please describe.**
Currently if user set new upload and download torrent speed then user not notified about setting new speed.

**Describe the solution you'd like**
Add snackbar on set new upload and download speed.

**Are you working on this? (Yes/No)**
Yes

**Comment by puranikvinit** [comment]
I'd love to work on this issue. Can you please assign this to me?
