### ISSUE TITLE
Any chance to get updates?

### ISSUE THREAD

**Issue by reinethernal** [CCExtractor/Flood_Mobile#190]
Hi!
First of all, thank you for an app !
My question is - is there any chance to move forward from alpha stage fixing bugs with ui, etc? It's impossible to do anything but view status of downloads.
Please, let me know if you don't forget about your project!

**Comment by Akshatji800** [comment]
Hello @reinethernal  we will soon publish an update which would be fixing most of the existing issues. Thanks for your patience.

**Comment by reinethernal** [comment]
@Akshatji800 Thank you!

**Comment by reinethernal** [comment]
Hi! Any news?

**Comment by Akshatji800** [comment]
> Hi! Any news?

Hello @reinethernal you can expect an update soon.

**Comment by Akshatji800** [comment]
> Hi! Any news?

Hello @reinethernal , just released a new version of Flood-Mobile. If interested feel free to use it and let me know your experience. Criticism is also welcomed.
https://github.com/CCExtractor/Flood_Mobile/releases/tag/v1.0.0-beta

**Comment by reinethernal** [comment]
@Akshatji800 Wow, thanks for the update! Unfortunately I still can't add files to upload through the app, maybe I'm doing something wrong. I'll post later on the results. Thanks again for your hard work!

**Comment by Akshatji800** [comment]
> @Akshatji800 Wow, thanks for the update! Unfortunately I still can't add files to upload through the app, maybe I'm doing something wrong. I'll post later on the results. Thanks again for your hard work!

Please let me know what issues you are facing exactly while trying to add a torrent. I will be happy to help you resolve the issue.

**Comment by Akshatji800** [comment]
Closing this issue as I feel the deliverables of the issue has been fulfilled after the last release. @reinethernal if you still have any issues you are welcome to create a new issue for that as well.
