### ISSUE TITLE
Torrent doesn't get removed from device notifications after deleting.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#195]
**Describe the bug**
Torrent doesn't get removed from device notifications after deleting.

**To Reproduce**

1. Go to homepage and add a torrent.
2. A device notification will be displayed on showing the torrent download progress.
3. Navigate back to homepage and delete the torrent.
4. The notification doesn't get removed.

**Expected behavior**
The device notification should be removed on deleting the torrent.

**Comment by manoj1749** [comment]
Can you assign me this issue?

**Comment by Akshatji800** [comment]
> Can you assign me this issue?

Sure @manoj1749 assigning this issue to you.

**Comment by adilwahla** [comment]
@Akshatji800  I will fix this
