### ISSUE TITLE
Theme bug in RSS-Feed's browse feeds option torrents display.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#196]
**Describe the bug**
Theme bug in RSS-Feed's browse feeds option torrents display.

**To Reproduce**

1. Go to homepage and click add rss feed button on top right.
2. Add a rss-feed and select that feed label under the browse feeds option.
3. See the list displaying torrents have its borders as nearly invisible in the light mode of the app.

**Expected behavior**
Borders should be visible in light mode as well.

**Screenshots**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/222991574-54e40aed-e238-4e69-88a6-29f68abb2e6c.jpg" width="250"> <br /><b>Dark-Mode(RSS-Feed)</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/222991591-17320b91-c388-4e8d-b14f-259826136543.jpg" width="250"><br /><b>Light-Mode(RSS-Feed with theme bug)</b></a><br /></td>
</tr>
</table>

**Comment by sher999** [comment]
Can you assign this issue to me I want work on it.

**Comment by Akshatji800** [comment]
> Can you assign this issue to me I want work on it.

Sure @sher999 assigning this issue to you.

**Comment by aryamanshrivastava** [comment]
Can you please assign this issue to me, I want work on it.
