### ISSUE TITLE
RSS-Feed getting added on UI screen even without any connection to backend.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#197]
**Describe the bug**
If a user does not run the flood backend and tries to add an rss feed the feed gets added to the app rss-feed UI list which should not happen and an error should be returned.

**To Reproduce**

1. Go to homepage and click add rss-feed button on the top right.
2. Add a rss-feed without running the flood backend.
3. The rss-feed feed get displayed in the rss-feed list in the app's UI.

**Expected behavior**
If flood backend is not running then the rss-feed should not get added to the app's rss-feed UI showing existing added rss-feed and instead should remind the user to connect to the backend by displaying a message/toast etc.

**Comment by sher999** [comment]
Can you assign this issue to  me I want work on it.

**Comment by Akshatji800** [comment]
@sher999 please take one issue at a time. I am happy to assign you this issue as well once you successfully make a PR solving the previous issue assigned to you.

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by rokr1590** [comment]
Hey there @Akshatji800 Can i work on this ... please ?

**Comment by adilwahla** [comment]
@Akshatji800 assign this to me I will fix it
