### ISSUE TITLE
RSS-Feed page textfields doesn't get reset after saving/adding the rss-feed.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#198]
**Describe the bug**
RSS-Feed page textfields doesn't get reset after saving/adding the rss-feed.

**To Reproduce**

1. Go to homepage and click on add rss-feed button on the top right.
2. Add a rss-feed.
3. The add rss-feed page's textfields does not get reset even after that rss-feed is successfully added.

**Expected behavior**
The textfields should get reset after successfully adding the rss-feed.

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by Akshatji800** [comment]
> Can I work on this ?

Sure @Sudhanva-Nadiger I will assign this issue to you.

**Comment by aryamanshrivastava** [comment]
@Akshatji800 can you please assign this issue to me, I love to work on it

**Comment by Sudhanva-Nadiger** [comment]
Hey @aryamanshrivastava the pull request solving this has already been made! Look at the other issues, or open a new issue if u find any in the app ! And you can start working on it . 
Thanks
