### ISSUE TITLE
Widget doesn't adapt to light mode

### ISSUE THREAD

**Issue by virajbhartiya** [CCExtractor/Flood_Mobile#209]
**Describe the bug**
After enabling light mode, if we choose to add a magnet link, the widget's color doesn't change according to light mode. It can be understood with the screenshot attached below
![image](https://user-images.githubusercontent.com/56783451/223929414-3bbaf19e-9981-4a9c-8d02-65c32fbd970b.jpeg)

**To Reproduce**

1. Switch to the light mode
2. Click in the "+" icon on the home screen 
3. choose a magnet link
4. See the error

- OS: Tested on an Android emulator

**Comment by amitamrutiya2210** [comment]
Hey @virajbhartiya, this issue has already been solved with this PR #147. Fetch the latest changes and run it, then your issue will be solved.

**Comment by virajbhartiya** [comment]
Okay, I'll close this issue then.
