### ISSUE TITLE
Add Sound Null Safety at various places in codebase

### ISSUE THREAD

**Issue by GeekyPS** [CCExtractor/Flood_Mobile#210]
**Describe the bug**
Few null checks issues in packages/flutter_client_sse/lib/

**To Reproduce**

1. Ensure your device is on latest stable channel of flutter i.e 3.7.7
2. flutter pub get
3. flutter run

**Expected behavior**
Due to unitialized non-nullable variables the code does not compile on latest version of flutter

**Device Information [optional]:**

- OS: iOS

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aryamanshrivastava** [comment]
@GeekyPS please assign this issue to me.

**Comment by aryamanshrivastava** [comment]
@GeekyPS can you please assign this issue to me.

**Comment by himanshu21072002** [comment]
Hello, 
I am a flutter developer and have 2 years of experience . I want to solve this issue. So can you please assign this issue to me.
thanks.

**Comment by abhishek09827** [comment]
@GeekyPS please assign this issue to me.
