### ISSUE TITLE
Provider to Bloc Migration 

### ISSUE THREAD

**Issue by adilwahla** [CCExtractor/Flood_Mobile#215]
**Describe the  enhancement**
As a contributor  of flood app, I would like to request an enhancement to migrate from Provider to Bloc state management architecture in order to improve performance and simplify the codebase.

Currently, our app uses Provider to manage state, but we believe that migrating to Bloc will provide significant benefits in terms of better separation of concerns, easier testing, and improved performance. We have already identified several areas of our codebase where this migration could be beneficial.

However, we recognize that this migration will require significant changes to our codebase

The Bloc (Business Logic Component) pattern is a popular state management solution that helps to separate business logic from presentation logic. The Bloc pattern allows to easily manage and update the state of application, making it more predictable and easier to maintain.

![download](https://user-images.githubusercontent.com/48839911/229919399-c0a908dd-a6ed-46c2-9494-82d8ec8c9cc5.png)

**And why would  migrate away from Provider?** 

While there is much love for Provider, there are also much challenges

- Provider is a loosely structured framework that can lead to unruly code.
- ChangeNotifierProviders make your data available to descendants. This architectural approach is usually great but can be challenging when widgets on another branch need the data.
- Provider’s static of command listens to changes by default. This can lead to unnecessary widget rebuilds.

**Why Bloc**
[Business Logic Components](https://pub.dev/packages/flutter_bloc) is a Flutter architecture much more similar to popular solutions in mobile such as [MVP or MVVM.](https://www.miquido.com/blog/mvc-mvp-mvvm/) It provides separation of the presentation layer from business logic rules. This is a direct application of the declarative approach which Flutter strongly emphasizes i.e. UI = f (state). BLoC is a place where events from the user interface go. Within this layer, as a result of applying business rules to a given event, BLoC responds with a specific state, which then goes back to the UI. When the view layer receives a new state, it rebuilds its view according to what the current state requires.

**Overall Steps to follow**

- Install flutter_bloc and provider packages.
- Identify parts of the app currently using Provider.
- Decide which parts of the app will be migrated to Bloc.
- Create Blocs for the selected parts using bloc package.
- Refactor code to use the Blocs instead of Providers.
- Update UI to use the new Blocs.
- Test app for issues and make necessary changes.

**Are you working on this issue? (Yes/No)**
YES

**Comment by Sudhanva-Nadiger** [comment]
Hi @adilwahla ! What you are doing is great 👍🏻! Since it's a big architecture change of the code base I suggest you to wait until @Akshatji800 or any members of the organization approval!

**Comment by adilwahla** [comment]
I understand
