### ISSUE TITLE
Revise qBittorrent Instructions and Clarify Environment Setup in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tb-rules10** [CCExtractor/Flood_Mobile#258]
### Problem Description

In the `Contribution.md` file, qBittorrent is mentioned at the top. However, Flood has difficulty connecting to qBittorrent, especially versions beyond 4.4.3. This creates confusion for new contributors who face challenges setting up the environment for this project.

### Proposed Solution
To address this, we suggest either of the following options:

1. Remove the instructions for qBittorrent from the `CONTRIBUTING.md` file. Retain instructions only for Transmission.
   
   **OR**

2. Shift the qBittorrent instructions below the Transmission instructions in the `CONTRIBUTING.md` file.
   
   **OR**

3. Add instructions for setting up rTorrent in the `CONTRIBUTING.md` file, alongside the instructions for Transmission.

### Are you working on this issue? (Yes/No)
If you find this issue relevant, I can start working on it.

**Comment by Akshatji800** [comment]
I don't find this as a legit issue. I have been using qBittorrent and it works pretty well. If you face some issues with it and find a way to resolve that then please create a issue for that and we can move forward with that but making changes suggested for resolving the issue is not a correct way.

**Comment by tb-rules10** [comment]
Okay, I'll surely keep it in mind from next time.
