### ISSUE TITLE
Filter torrent based on the completion status

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/Flood_Mobile#26]
Issue:
Currently, the only way to filter torrents is through the name. An additional way to filter the torrent based on the completion status (Completed, Downloading, Paused) would be helpful.

Solution:
A bottom sheet that is toggled with an icon adjacent to the search bar with options to choose between the filtering options.

Note: Any other solution or approach on how this could be implemented from a design or implementation perspective is also welcome.

**Comment by yatendra2001** [comment]
Hi I can remove this issue, could you please assign it to me?

**Comment by pratikbaid3** [comment]
@yatendra2001 I am assigning this issue to you. For the UI it is suggested that you make changes to the Figma mockup first before proceeding with implementation.

**Comment by pratikbaid3** [comment]
https://www.figma.com/file/XkJodgrffnkniBQF3bIEZS/Flood

**Comment by yatendra2001** [comment]
Thank you @pratikbaid3 for assigning it to me, Also I am participating in hacktober this year, So could you please add hacktoberfest tag as well?

**Comment by yatendra2001** [comment]
Thank you @pratikbaid3 for assigning, Also I am participating in hacktober this year, So could you please add hacktoberfest tag as well?

**Comment by pratikbaid3** [comment]
I'll add the tag on your pr.

**Comment by yatendra2001** [comment]
Hi @pratikbaid3 , I have gone through all the steps in contributing.md still i am unable to login to the main app, could you please help?

**Comment by pratikbaid3** [comment]
@yatendra2001 Please join and post your issue in the slack group (Link in the readme). It would be easier for me and other contributors to help you out there.

**Comment by yatendra2001** [comment]
@pratikbaid3 I am trying to join slack group but the link is not working don't know why.

**Comment by pratikbaid3** [comment]
@yatendra2001, please provide your email id, I'll send you a invite.

**Comment by yatendra2001** [comment]
@pratikbaid3, my email id is yatendra2001kumar@gmail.com

**Comment by Akshatji800** [comment]
Is anyone still working on this issue? If not then @pratikbaid3 can you please assign it to me.

**Comment by yatendra2001** [comment]
Hey @Akshatji800 , I have made quite some progress on it, could not update the issue due to college exams and unplanned circumstances, I will raise a PR soon. Until then we can collaborate on it.

**Comment by pratikbaid3** [comment]
@yatendra2001 If you are not working on this issue, please let me know. I'll assign it to someone else.

**Comment by yatendra2001** [comment]
Sure, I am actually working on something else for a while now, You may assign it to someone else. @pratikbaid3

**Comment by Akshatji800** [comment]
@pratikbaid3 Sir can you please assign this to me. I will try my best to solve this issue asap.
