### ISSUE TITLE
Application out of date

### ISSUE THREAD

**Issue by Sudarshan-21** [CCExtractor/Flood_Mobile#261]
**Describe the bug**
This application is incompatible with Android 11

- OS: Android
- 
![WhatsApp Image 2024-02-17 at 12 18 35 PM](https://github.com/CCExtractor/Flood_Mobile/assets/137636943/0e3b6f4a-2b29-4d86-8d2d-470f8b379a3d)

**Comment by amitamrutiya** [comment]
Hey @Sudarshan-21 try our latest release flood mobile application. It is compatible with latest android version. 

https://play.google.com/store/apps/details?id=com.ccextractor.floodmobile_flutter

**Comment by Sudarshan-21** [comment]
> Hey @Sudarshan-21 try our latest release flood mobile application. It is compatible with latest android version.
> 
> https://play.google.com/store/apps/details?id=com.ccextractor.floodmobile_flutter

Thank you so much for replying.
