### ISSUE TITLE
Local notification

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/Flood_Mobile#27]
Feature: 
A local notification that allows the user to start/stop torrent download without opening the app. This could also be triggered when the download completes or a new torrent is added.

Solution:
Local Notification: https://pub.dev/packages/flutter_local_notifications
Awsome Notification: https://pub.dev/packages/awesome_notifications

**Comment by yatendra2001** [comment]
I can remove this issue, could you please assign it to me?

**Comment by pratikbaid3** [comment]
@adizcode I am assigning this issue to you. Please refer to the awsome_notification documentation and let me know if you any help.

**Comment by pratikbaid3** [comment]
Also please make a new branch from the develop branch.

**Comment by adizcode** [comment]
@pratikbaid3 Thank you, I will.

**Comment by msubham193** [comment]
@adizcode are u working on this issue if not then i will work on this issue

**Comment by adizcode** [comment]
@msubham193 Yeah. I had made quite some progress, but couldn't get the notifications to work when the app is closed.

@pratikbaid3 Is collaborating with another dev an option?

**Comment by adizcode** [comment]
@pratikbaid3 Removed my assignment as I hadn't worked on this in a long time.
Perhaps someone else can take this up.

**Comment by Akshatji800** [comment]
Feature implemented and a [PR](https://github.com/CCExtractor/Flood_Mobile/pull/94) was made which is already merged.
