### ISSUE TITLE
Logout popup

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/Flood_Mobile#28]
Feature:
When the user clicks on the logout button on the side drawer, a popup should be shown confirming if the user is sure they want to log out.

**Comment by arq0017** [comment]
I would like to look into this issue .

**Comment by pratikbaid3** [comment]
@arq0017 It would be suggested that you create a design for the popup before implementing it in code. You can use https://www.figma.com/file/XkJodgrffnkniBQF3bIEZS/Flood?node-id=0%3A1 as a reference and also join the CCExtractor slack channel to discuss further

**Comment by arq0017** [comment]
@pratikbaid3 I have designed the prototypes. Shared on slack as well. 
Link - [Logout popup design ](https://www.figma.com/file/cbK0obHDwWIZ5ej37IDjaS/Flood-Copy?node-id=501%3A3)

**Comment by arq0017** [comment]
@pratikbaid3 created a pull request. Please let me know where I can improve. Thank you!

**Comment by pratikbaid3** [comment]
@arq0017 Thank you for the PR
