### ISSUE TITLE
Snack bar

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/Flood_Mobile#30]
Issue:
Currently, the app does not provide the user any instant feedback when they add, delete or complete a torrent. There are several other scenarios where a snack bar will be relevant (suggestions needed)

These are some of the actions where a snack bar could be added:

- [ ] Add torrent
- [ ] Remove torrent
- [ ] Change the app settings
- [ ] Create a new user on the settings page
- [ ] Setting the priority of selected torrent content

**Comment by arq0017** [comment]
Hey , i would like to work on this issue .

**Comment by arq0017** [comment]
> Hey , i would like to work on this issue .

Please note that i am working on mac . Therefore as per contribution readme , i m not able to download qtorrent . Is there any other way to do so ?

**Comment by pratikbaid3** [comment]
@arq0017 I am assigning the issue to you. Also, qBitTorrent is available on mac.

**Comment by Ashish-AI** [comment]
@pratikbaid3 Shall I raise a PR for the same, I believe @arq0017 is not available. If he comes with a PR, we can merge it, if needed.

**Comment by Ashish-AI** [comment]
It would be nice. What's your thought on writing code for our own snackbar @pratikbaid3 . 
**Advantage:**
```
We will not be dependent on an external library( which may depend on some other library) 
This will help in reducing the size of our app.
Will follow our own color theme.
Can be customized according to our need.
```

**Comment by KunjKanani** [comment]
@Ashish-AI Are you still working on this issue? @pratikbaid3 If not, Then I want to work on it.

**Comment by Ashish-AI** [comment]
Hey @KunjKanani , I am working on it. Could not update the issue due to unplanned personal commitments. PR will be raised soon.

**Comment by KunjKanani** [comment]
@Ashish-AI Are you still working on this issue?

**Comment by Ashish-AI** [comment]
@KunjKanani  I have worked on it only and is almost done. There is a gap as I mentioned due to some personal issues. PR will be raised shortly.

**Comment by Akshatji800** [comment]
@Ashish-AI are you still working on this issue? If not, @pratikbaid3 Sir, can you please assign this issue to me. I will try to solve this issue asap.

**Comment by Ashish-AI** [comment]
@pratikbaid3 PR has been raised.
