### ISSUE TITLE
Partially Implemented Check Hash

### ISSUE THREAD

**Issue by KunjKanani** [CCExtractor/Flood_Mobile#42]
@pratikbaid3 We have a _**check hash**_ option in each displayed torrent. It does not give any confirmation when we perform a check hashed operation. We can give confirmation by toast.

**Comment by Akshatji800** [comment]
A confirmation can be given by implementing a snackbar.

**Comment by divz-codess** [comment]
Hey @Akshatji800 can you please assign this issue to me?

**Comment by Akshatji800** [comment]
@divz-codess assigning this issue to you. Hope to see a PR soon.
