### ISSUE TITLE
Graph that represents the upload and the download speed.

### ISSUE THREAD

**Issue by Procoder16** [CCExtractor/Flood_Mobile#45]
The **Flood Web UI** has a graph on the left side of the screen that depicts the upload and the download speed. I want to implement a similar graph(rather a chart) for the same purpose keeping in consideration the Web UI and the Mobile UI theme.

**Comment by Procoder16** [comment]
@pratikbaid3 sir, I am already working on it, kindly assign me this!

**Comment by Akshatji800** [comment]
Please design a UI on figma showing the whole user interface after the graph gets implemented.

**Comment by amitamrutiya2210** [comment]
@Akshatji800 What you say about this type of graph that represents the upload and the download speed.

![iPhone 14 Pro - 1 (1) (Custom)](https://user-images.githubusercontent.com/91112485/210515316-885d9eb7-ff06-4443-873d-98194d96c3bb.png)

**Comment by amitamrutiya2210** [comment]
@Akshatji800 can you assign this task to me? I can implement graph.
