### ISSUE TITLE
Simple UI bug in logout alert dialog

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#48]
**Bug Description**
There is a simple UI bug in logout alert dialog. The 'Yes' and 'No' buttons are not displayed as it should.

**To Reproduce**

1. Go to 'options by sliding the main dashboard towards right'
2. Click on 'Logout'
3. See error in 'Yes' and 'No' button alignment.

**Expected behavior**
The 'Yes' and 'No' button should be aligned side by side.

**Screenshots**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/146689396-87911408-fd20-40a3-ac8a-b3bf1625ca3e.jpg" width="200"> <br /><b>Present State</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/146689984-13a22248-0952-4944-8f79-3668e8bb9122.jpg" width="200"><br /><b>How it should look</b></a><br /></td>
</tr>
</table>

**Device Information**

- OS: [Android-11]
- Device Name: realme 7 pro

**Are you working on this issue? (Yes)**

**Comment by pratikbaid3** [comment]
I am unable to recreate the bug in the given device.

**Comment by Akshatji800** [comment]
@pratikbaid3 Sir I too just now tested the logout-alert dialog in other emulators and I was not able to create the issue but it comes in my device. The PR I made solves the issue for my device and does not effect the present state of logout-alert dialog in other devices also.

**Comment by pratikbaid3** [comment]
Closing issue #50 because it cannot be replicated
