### ISSUE TITLE
Overflow issue in main dashboard screen

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#49]
**Bug Description**
Overflow issue in main dashboard screen

**Expected behavior**
Should not overflow

**Screenshots**
![overflow](https://user-images.githubusercontent.com/73401649/146690340-5e6ac0dc-2f93-4fd1-8c52-0ad2e6c73b06.jpg)

**Device Information**

- OS: [Android-11]
- Device Name: realme 7 pro

**Are you working on this issue? (Yes)**

**Comment by shardulinamdar4** [comment]
I would like to take this issue

**Comment by Akshatji800** [comment]
@shardulinamdar4 actually I solved the issue after reporting it and I am just waiting for @pratikbaid3 to approve it. The same goes for the other issue I reported.
