### ISSUE TITLE
Null checks and initialization erorrs.

### ISSUE THREAD

**Issue by Pavel401** [CCExtractor/Flood_Mobile#52]
**Describe the bug**

- The non-nullable variable '_client' must be initialized.Try adding an initializer expression.
- A value of type 'RegExpMatch?' can't be assigned to a variable of type 'Match'.
- The property 'isEmpty' can't be unconditionally accessed because the receiver can be 'null'.
Try making the access conditional (using '?.') or adding a null check to the target ('!').
-null checks

**To Reproduce**

1. Go to 'flutter_client_sse.dart'
4. See an error.

**Expected behavior**
There should be no errors.

**Screenshots**

![er](https://user-images.githubusercontent.com/47685150/147823357-f37525ed-6bfd-44a8-a9fd-c80be9f6d777.png)

**Are you working on this issue? (Yes/No)**
**Yes**

**Comment by pratikbaid3** [comment]
@Pavel401 I have assigned this issue to you.

**Comment by pratikbaid3** [comment]
Hi @Pavel401. The latest version of the package has these errors fixed. Closing this since this is not Flood specific.
