### ISSUE TITLE
Unable to change default download directory

### ISSUE THREAD

**Issue by pete2583** [CCExtractor/Flood_Mobile#56]
**Describe the bug**

Unable to update default download folder

**To Reproduce**

1. Go to settings
2. Click on resources
3. Select "default download..."
4. Try and change the address

**Expected behavior**
You're able to change the address. 

You are unable to delete the address and only have the option of keying numbers, which you can't actually press. 

**Screenshots**

![Screenshot_20220124-215611](https://user-images.githubusercontent.com/58146764/150872613-96398321-fd08-4368-8c64-f67ee22dab41.png)

**Device Information [optional]:**

- OS: Android

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by raysummee** [comment]
I gone through this. The keyboard should be alphabetic but numeric, both for iOS and android. It's easy to fix.

I want to fix this issue.

**Comment by pratikbaid3** [comment]
@pete2583 Thanks for pointing this out. I am assigning it to @raysummee.

**Comment by raysummee** [comment]
I want to also highlight that not only default directory. Many field are not able to save on setting page. They got reset when clicked save. 

The keyboard issue is solved by the way. 
Should I fixed them also?

There is the screen recording below.

https://user-images.githubusercontent.com/52542371/151694598-9cce4f48-17a2-490c-8d7b-9dc5a0feb723.mp4

**Comment by pratikbaid3** [comment]
@raysummee Please create a separate issue for all other changes and a separate PR.

**Comment by pratikbaid3** [comment]
This PR should be only specific to the issue of the default directory.

**Comment by raysummee** [comment]
Sure. Thank you.

**Comment by raysummee** [comment]
I have submitted a pull request. Please check if any changes required.

**Comment by pratikbaid3** [comment]
Fixed by #58
