### ISSUE TITLE
Unable to update many fields in setting page. 

### ISSUE THREAD

**Issue by raysummee** [CCExtractor/Flood_Mobile#60]
**Describe the bug**
Unable to update some fields in setting page. After updating fields, if I click save all the updated fields are reset. 

In the screen recording below you can see. Some fields are updating, many are not.

**To Reproduce**

1. Open setting page.
2. Click on Bandwidth
3. Change value of global download rate throttle (or any, some fields works. Some don't)
4. Click save
5. The value will be reset

**Expected behavior**
When click save. The value should be updated with the value user has put, Not reset.

**Screenshots**

https://user-images.githubusercontent.com/52542371/151696332-4abcd026-55e5-4fcc-9dbd-ca1d775c1f13.mov

**Device Information [optional]:**

- OS:  iOS
- Type: Simulator

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by ItsAdityaKSingh** [comment]
Can I take up this issue @pratikbaid3 ?

**Comment by ALIRAZA17** [comment]
Can I work on this issue @pratikbaid3?

**Comment by amitamrutiya2210** [comment]
Request for assigned this issue @pratikbaid3 or @Akshatji800.
