### ISSUE TITLE
label of setting input field not visible

### ISSUE THREAD

**Issue by raysummee** [CCExtractor/Flood_Mobile#61]
**Describe the bug**
When in dark mode. The label of text field(input field) in setting page are not quite visible. The colour of label is black in dark background, for which it is hard to see the input.

**To Reproduce**

1. Toggle dark mode
2. Go to setting page
3. collapse Bandwidth (or any)
4. below sub heading (Transfer rate throttle or any )
5. The label is black in dark background, less visibility (Global download rate throttle)

**Expected behavior**
The label should be white in dark background (dark mode)

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2022-02-01 at 12 14 04](https://user-images.githubusercontent.com/52542371/151924102-ed679025-5d5a-4f37-9cf1-a93081833911.png)

**Device Information [optional]:**

- OS: iOS simulator 

**Additional context**

**Are you working on this issue? (Yes/No)**
yes

**Comment by raysummee** [comment]
@pratikbaid3 please assign me this issue. I already opened a pull request #62 . Please check that too. Thanks

**Comment by pratikbaid3** [comment]
#62
