### ISSUE TITLE
Display applied filter information on the home screen

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#69]
**Feature Request:**
- To display applied filter information on the home screen.

**Feature request reason:**
- It is very frustrating to each time open the filter menu to see which filter is applied so to solve this issue it is better to display the applied filter information on the home screen.

**Solution:**
- To display applied filter information on the home screen

**Solution Demonstration Screenshot:**
<table>
<tr>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/153948492-5a4b6c0b-b71a-4c0d-9494-9b2924026b72.jpg" width="250"> <br /><b>Demo-1</b></a><br /></td>
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/153948503-002efa04-60d9-4541-aacc-15f71fde0ee7.jpg" width="250"><br /><b>Demo-2</b></a><br /></td>
</tr>
</table>

**Are you working on this? (Yes)**

**Comment by pratikbaid3** [comment]
This is a good use case but the UI doesn't look great. The primary objective is to have the majority of the screen real estate for torrents but the filter text is taking up too much space.

**Comment by Akshatji800** [comment]
https://user-images.githubusercontent.com/73401649/154589696-9d982c64-b019-43e1-82f2-6173e163c90d.mp4

@pratikbaid3 Sir does the UI looks okay now?
