### ISSUE TITLE
Display the number of torrents that will be appearing after applying a filter.

### ISSUE THREAD

**Issue by Akshatji800** [CCExtractor/Flood_Mobile#73]
**Description:**
For better user experience and ease the number of torrents that will be appearing after applying a filter should be displayed beside the filter option as displayed in the Flood WebApp.

**Describe the solution you'd like**
To display the number of torrents that will be appearing after applying a filter.

**Demo Screenshot:**
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/154165420-149b3eb8-2e5f-4434-95b3-f174aa7a8f64.jpg" width="250"> </td>

**Are you working on this? (Yes)**

**Comment by pratikbaid3** [comment]
Looks like a good use case although the UI doesn't look too good. We can obviously work around that.

**Comment by Akshatji800** [comment]
https://user-images.githubusercontent.com/73401649/154766963-1d2e88d4-e422-4131-a64a-adf8041f2e05.mp4

@pratikbaid3 Sir how does the UI look now?

**Comment by Akshatji800** [comment]
<td align="center"><img src= "https://user-images.githubusercontent.com/73401649/154767233-6a27a504-a1d5-4bae-8715-c50ee256ec48.jpg" width="250"> </td>
 
Another option can be to use this as the color for the selected filter. @pratikbaid3 Sir
